export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_SESSION_ID = 'UPDATE_SESSION_ID';
export const LOGOUT = 'LOGOUT';
export const UPDATE_FAVORITE_MOVIES = 'UPDATE_FAVORITE_MOVIES';
export const UPDATE_WATCH_LIST_MOVIES = 'UPDATE_WATCH_LIST_MOVIES';